services:
  - type: web
    name: django-stripe-shop
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: "shop"
      - key: DB_USER
        fromDatabase:
          name: postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres-db
          property: port
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        value: "pk_test_51RWMw6IpcH9lBRyH0xXZZqvwRs6x3iAn1VmV283yHGuRQpGWJdtApriq1K4vszoalUeTzKGDkLasqn16kTX3Xet200An30QIc7"

databases:
  - name: postgres-db
    databaseName: shop
    user: shop_user
    plan: free